package io.contentpublisher.platform.domain;

public enum ChannelType {
    DEV,
    WORDPRESS,
    DISCOURSE,
    GITHUB_DISCUSSIONS,
    X,
    REDDIT,
    HASHNODE,
    MEDIUM,
    MASTODON,
    GHOST,
    XIAOHONGSHU,
    CSDN,
    JUEJIN,
    ZHIHU,
    CNBLOGS,
    SEGMENTFAULT,
    V2EX,
    OSCHINA,
    LINKEDIN,
    WECHAT_OFFICIAL,
    JIANSHU,
    TOUTIAO,
    BILIBILI_COLUMN,
    BLOG_51CTO,
    TENCENT_CLOUD,
    ALIBABA_CLOUD,
    HUAWEI_CLOUD
}
